# Generated by Django 4.0.5 on 2022-06-15 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upload_vid', '0003_alter_video_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='description',
        ),
        migrations.RemoveField(
            model_name='video',
            name='title',
        ),
        migrations.RemoveField(
            model_name='video',
            name='uploaded_at',
        ),
    ]
