# Generated by Django 4.0.5 on 2022-06-15 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload_vid', '0004_remove_video_description_remove_video_title_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('myfile', models.FileField(upload_to='videos/')),
            ],
        ),
        migrations.DeleteModel(
            name='Video',
        ),
    ]
